# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."mealie" = {
    image = "ghcr.io/mealie-recipes/mealie:latest";
    environment = {
      "ALLOW_SIGNUP" = "true";
      "BASE_URL" = "http://192.168.1.100:9925";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Berlin";
    };
    volumes = [
      "/home/hallow/containers/mealie/data:/app/data:rw"
    ];
    ports = [
      "9925:9000/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--memory=1048576000b"
      "--network-alias=mealie"
      "--network=mealie_default"
    ];
  };
  systemd.services."docker-mealie" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-mealie_default.service"
    ];
    requires = [
      "docker-network-mealie_default.service"
    ];
    partOf = [
      "docker-compose-mealie-root.target"
    ];
    upheldBy = [
      "docker-network-mealie_default.service"
    ];
    wantedBy = [
      "docker-compose-mealie-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-mealie_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f mealie_default";
    };
    script = ''
      docker network inspect mealie_default || docker network create mealie_default
    '';
    partOf = [ "docker-compose-mealie-root.target" ];
    wantedBy = [ "docker-compose-mealie-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-mealie-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
