# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."Suwayomi-Server" = {
    image = "ghcr.io/suwayomi/suwayomi-server:v2.3.2298";
    ports = [
      "4568:4567/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=suwayomi_server"
      "--network=suwayomi_default"
    ];
  };
  systemd.services."docker-Suwayomi-Server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-suwayomi_default.service"
    ];
    requires = [
      "docker-network-suwayomi_default.service"
    ];
    partOf = [
      "docker-compose-suwayomi-root.target"
    ];
    upheldBy = [
      "docker-network-suwayomi_default.service"
    ];
    wantedBy = [
      "docker-compose-suwayomi-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-suwayomi_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f suwayomi_default";
    };
    script = ''
      docker network inspect suwayomi_default || docker network create suwayomi_default
    '';
    partOf = [ "docker-compose-suwayomi-root.target" ];
    wantedBy = [ "docker-compose-suwayomi-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-suwayomi-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
