# nix run github:aksiksi/compose2nix -- \
# -inputs=docker-compose.yml \
# -output=compose.nix \
# -include_env_files=false \
# -check_bind_mounts=true \
# -use_upheld_by=true \
# -runtime=docker \
# -project=suwayomi \
# -root_path=/home/hallow/containers/suwayomi
services:
  suwayomi_server:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    container_name: Suwayomi-Server
    # volumes:
      # The order matters! Downloads must come before the main Tachidesk folder.
      # - /example/suwayomi-server/downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      # - /example/suwayomi-server/files:/home/suwayomi/.local/share/Tachidesk
    ports:
      - 4568:4567
    restart: unless-stopped
