# nix run github:aksiksi/compose2nix -- \
# -inputs=docker-compose.yml \
# -output=compose.nix \
# -include_env_files=false \
# -check_bind_mounts=true \
# -use_upheld_by=true \
# -runtime=docker \
# -project=suwayomi \
# -root_path=/home/hallow/containers/suwayomi
services:
  suwayomi_server:
    image: ghcr.io/suwayomi/suwayomi-server:v2.3.2298
    container_name: Suwayomi-Server
    # user: "1001:100"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4568:4567"
    restart: unless-stopped

  syncyomi:
    image: ghcr.io/syncyomi/syncyomi:latest
    container_name: SyncYomi
    # user: "1001:100"
    ports:
      - "8282:8282"
    environment:
      - TZ=Europe/Berlin
      # SyncYomi needs to communicate with Suwayomi
      - SUWAYOMI_URL=http://suwayomi_server:4567
    volumes:
      - ./syncyomi-data:/data
    depends_on:
      - suwayomi_server
    restart: unless-stopped
