# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."paperless-broker" = {
    image = "docker.io/library/redis:8";
    environmentFiles = [
      "/home/hallow/paperless/.env"
    ];
    volumes = [
      "paperless_redisdata:/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=broker"
      "--network=paperless_default"
    ];
  };
  systemd.services."docker-paperless-broker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_redisdata.service"
    ];
    requires = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_redisdata.service"
    ];
    partOf = [
      "docker-compose-paperless-root.target"
    ];
    upheldBy = [
      "docker-network-paperless_default.service"
      "docker-volume-paperless_redisdata.service"
    ];
    wantedBy = [
      "docker-compose-paperless-root.target"
    ];
  };
  virtualisation.oci-containers.containers."paperless-db" = {
    image = "docker.io/library/postgres:17";
    environment = {
      "POSTGRES_DB" = "paperless";
      "POSTGRES_PASSWORD" = "paperless";
      "POSTGRES_USER" = "paperless";
    };
    environmentFiles = [
      "/home/hallow/paperless/.env"
    ];
    volumes = [
      "/home/hallow/paperless/db-paperless:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=db"
      "--network=paperless_default"
    ];
  };
  systemd.services."docker-paperless-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-paperless_default.service"
    ];
    requires = [
      "docker-network-paperless_default.service"
    ];
    partOf = [
      "docker-compose-paperless-root.target"
    ];
    upheldBy = [
      "docker-network-paperless_default.service"
    ];
    wantedBy = [
      "docker-compose-paperless-root.target"
    ];
  };
  virtualisation.oci-containers.containers."paperless-webserver" = {
    image = "ghcr.io/paperless-ngx/paperless-ngx:latest";
    environment = {
      "PAPERLESS_DBHOST" = "db";
      "PAPERLESS_OCR_LANGUAGE" = "deu+eng";
      "PAPERLESS_REDIS" = "redis://broker:6379";
      "PAPERLESS_SECRET_KEY" = "=IqNKaXGQCy>.KXwyC-Qo<vZ>*b[f1duy{a_A=-23BE/Z8fAOo+ryn{qnI{xHbO/";
      "PAPERLESS_TIME_ZONE" = "Europe/Berlin";
      "USERMAP_GID" = "100";
    };
    environmentFiles = [
      "/home/hallow/paperless/.env"
      "/home/hallow/paperless/docker-compose.env"
    ];
    volumes = [
      "/home/hallow/paperless/consume:/usr/src/paperless/consume:rw"
      "/home/hallow/paperless/data-paperless:/usr/src/paperless/data:rw"
      "/home/hallow/paperless/export:/usr/src/paperless/export:rw"
      "/home/hallow/paperless/media:/usr/src/paperless/media:rw"
    ];
    ports = [
      "8452:8000/tcp"
    ];
    dependsOn = [
      "paperless-broker"
      "paperless-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=webserver"
      "--network=paperless_default"
    ];
  };
  systemd.services."docker-paperless-webserver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-paperless_default.service"
    ];
    requires = [
      "docker-network-paperless_default.service"
    ];
    partOf = [
      "docker-compose-paperless-root.target"
    ];
    upheldBy = [
      "docker-network-paperless_default.service"
      "docker-paperless-broker.service"
      "docker-paperless-db.service"
    ];
    wantedBy = [
      "docker-compose-paperless-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-paperless_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f paperless_default";
    };
    script = ''
      docker network inspect paperless_default || docker network create paperless_default
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-paperless_redisdata" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect paperless_redisdata || docker volume create paperless_redisdata
    '';
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-paperless-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
