# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."technitium" = {
    image = "technitium/dns-server:latest";
    environment = {
      "DNS_SERVER_ADMIN_PASSWORD" = "password";
      "DNS_SERVER_DOMAIN" = "dns-server";
    };
    volumes = [
      "/home/hallow/containers/technitium/data:/etc/dns:rw"
    ];
    ports = [
      "5380:5380/tcp"
      "53:53/udp"
      "53:53/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--hostname=technitium"
      "--network-alias=dns-server"
      "--network=technitium_default"
      "--sysctl=net.ipv4.ip_local_port_range=1024 65535"
    ];
  };
  systemd.services."docker-technitium" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-technitium_default.service"
    ];
    requires = [
      "docker-network-technitium_default.service"
    ];
    partOf = [
      "docker-compose-technitium-root.target"
    ];
    upheldBy = [
      "docker-network-technitium_default.service"
    ];
    wantedBy = [
      "docker-compose-technitium-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-technitium_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f technitium_default";
    };
    script = ''
      docker network inspect technitium_default || docker network create technitium_default
    '';
    partOf = [ "docker-compose-technitium-root.target" ];
    wantedBy = [ "docker-compose-technitium-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-technitium-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
