format = '''
[╭─ ](bold blue)$directory$git_branch$git_status$nix_shell
[╰](bold blue)$character
'''

[directory]
truncation_length = 8
truncation_symbol = '…/'
style = 'bold blue'

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)](bold blue) '

[nix_shell]
impure_msg = '[impure ](bold red)'
pure_msg = '[pure ](bold green)'
unknown_msg = '[unknown ](bold yellow)'
format = 'via $state '
