# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # espanso status
  - trigger: ":espanso"
    replace: "espanso is running"
  - trigger: "!isalive"
    replace: "espanso is running"

  # shorthand for commands
  - trigger: ":rebuild"
    replace: "sudo nixos-rebuild switch --impure --flake ~/nixos"

  # games
  - trigger: ":poe-busy"
    replace: "I am currently busy and will not be able to respond in time. Let me know if you are willing to wait"
  - trigger: ":poe-l"
    replace: "There is a high chance that you have the wrong league selected"
  - trigger: ":poe-bulk"
    replace: "Please use the bulk exchange tool on the website. It makes trading easies for both parties"

  # dates and time
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: ":now"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d@%H:%M"
  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%H:%M"

  # cmd outputs
  - trigger: "!shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"
  - trigger: ":paste"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo $(wl-paste)"


  - regex: :bc (?P<expr>.+ )=
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: echo "{{expr}}" | bc -l
